quarkus:
  http:
    port: 8082
  mongodb:
    connection-string: mongodb://localhost:27017
    database: inventory

  rest-client:
    "com.soitio.selfregister.client.RegistrationClient":
      url: http://localhost:8080
  index-dependency:
    selfregister:
      group-id: com.soitio.selfregister
      artifact-id: self-register-quarkus

service-discovery:
  service-name: inventory
  host: localhost
  port: 8082