quarkus:
  http:
    port: 8080
  mongodb:
    connection-string: mongodb://erp-mongodb:27017
    database: inventory
  rest-client:
    consul-api:
      url: http://erp-consul:8500
      scope: jakarta.inject.Singleton
  shutdown:
    timeout: PT5S

service-discovery:
  service-name: inventory
  host: inventory
  port: 8080