quarkus:
  http:
    port: 8082
  mongodb:
    connection-string: mongodb://localhost:27017
    database: inventory
  rest-client:
    gateway-api:
      url: http://localhost:8070/
      scope: jakarta.inject.Singleton

soitio:
  service: "http://localhost:8082"
  dependencies:
    - com.soitio.inventory.item.domain.InventoryItem
    - com.soitio.inventory.property.domain.Property
    - com.soitio.inventory.maintenance.domain.MaintenanceRecord
    - com.soitio.inventory.part.domain.Part