quarkus:
  http:
    port: 8080
  mongodb:
    connection-string: mongodb://erp-mongodb:27017
    database: inventory

  rest-client:
    "pl.mlisowski.inventory.selfregister.client.RegistrationClient":
      url: http://service-discovery:8080

service-discovery:
  service-name: inventory
  host: inventory
  port: 8080