quarkus:
  http:
    port: 8080
  mongodb:
    connection-string: mongodb://erp-mongodb:27017
    database: inventory
  rest-client:
    gateway-api:
      url: http://gateway:8080
      scope: jakarta.inject.Singleton
  shutdown:
    timeout: PT5S

soitio:
  service: "http://inventory:8080"
  dependencies:
    - com.soitio.inventory.item.domain.InventoryItem
    - com.soitio.inventory.property.domain.Property
    - com.soitio.inventory.maintenance.domain.MaintenanceRecord
    - com.soitio.inventory.part.domain.Part