quarkus:
  http:
    port: 8082
  mongodb:
    connection-string: mongodb://localhost:27017
    database: inventory
  rest-client:
    consul-api:
      url: http://consul.soitio-erp.com:8000/
      scope: jakarta.inject.Singleton

service-discovery:
  service-name: inventory
  host: localhost
  port: 8082