services:
  gateway:
    image: "erp/api-gateway:latest"
    depends_on:
      - erp-mongodb
    restart: unless-stopped
  fe:
    image: "erp/fe:latest"
    restart: unless-stopped
  erp-pg:
    image: "postgres:15.3-alpine3.18"
    environment:
      - POSTGRES_USER=erp
      - POSTGRES_PASSWORD=erp
    volumes:
      - /opt/postgres/erp-data:/var/lib/postgresql/data:Z
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:Z
    restart: unless-stopped
    user: "$UID:$GID"
  erp-mongodb:
    image: "mongodb/mongodb-community-server:6.0.7-ubi8"
    volumes:
      - /opt/mongodb/erp-data:/data/db:Z
    environment:
      MONGO_INITDB_DATABASE: inventory
    restart: unless-stopped
    user: "$UID:$GID"
  inventory:
    image: "erp/inventory:latest"
    depends_on:
      - erp-mongodb
      - gateway
    restart: unless-stopped
  finances:
    image: "erp/finances:latest"
    depends_on:
      - erp-pg
      - rabbit
      - gateway
    restart: unless-stopped
  # SFTP has some weird issues with permissions, even tho I tell it to use my UID and GUID it is using
  # podman auto generated which requires full access on public (chmod 757 for example)
  sftp:
    image: "atmoz/sftp"
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    volumes:
      - /opt/sftp/erp-data:/home/erp/data:z
      - /opt/sftp/erp-conf/users.conf:/etc/sftp/users.conf:ro
    userns: keep-id
    privileged: true
  purchase-scanner:
    image: "erp/purchase-scanner:latest"
    environment:
      SFTP_HOST: "sftp"
      SFTP_USERNAME: "erp"
      SFTP_PASSWORD: "admin"
      RABBITMQ_HOST: "rabbit"
      RABBITMQ_USERNAME: "erp-user"
      RABBITMQ_PASSWORD: "admin"
    restart: unless-stopped
    depends_on:
      - sftp
      - rabbit
  analytics:
    image: "erp/analytics:latest"
    restart: unless-stopped
    depends_on: 
      - rabbit
      - gateway
  dashboard:
    image: "erp/dashboard:latest"
    depends_on:
      - erp-mongodb
      - gateway
    restart: unless-stopped
  widgets-finances:
    image: "erp/widgets-finances:latest"
    depends_on:
      - dashboard
      - finances
      - inventory
      - gateway
    restart: unless-stopped
  reports-generator:
    image: "erp/reports-generator:latest"
    depends_on:
      - sftp
      - gateway
    restart: unless-stopped
  reports-service:
    image: "erp/reports-service:latest"
    depends_on:
      - erp-pg
      - reports-generator
      - gateway
  rabbit:
    image: "rabbitmq:3.13-management"
    volumes:
      - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbit/definitions.json:/etc/rabbitmq/definitions.json:ro
  nginx-proxy:
    image: "nginx:latest"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
      - /opt/sftp/erp-data:/mnt/data:ro
    restart: unless-stopped
    ports:
      - "8000:80"
