services:
  fe:
    image: "erp/fe:latest"
    restart: unless-stopped
  erp-pg:
    image: "postgres:15.3-alpine3.18"
    environment:
      - POSTGRES_USER=erp
      - POSTGRES_PASSWORD=erp
    volumes:
      - /opt/postgres/erp-data:/var/lib/postgresql/data:Z
      - ./sql/initialize_finances.sql:/docker-entrypoint-initdb.d/initialize_finances.sql:Z
    restart: unless-stopped
    user: "$UID:$GID"
  erp-mongodb:
    image: "mongodb/mongodb-community-server:6.0.7-ubi8"
    volumes:
      - /opt/mongodb/erp-data:/data/db:Z
    environment:
      MONGO_INITDB_DATABASE: inventory
    restart: unless-stopped
    user: "$UID:$GID"
  consul-client:
    image: "hashicorp/consul:1.18.2"
    restart: unless-stopped
    command: "agent"
    volumes:
      - ./consul/client.json:/consul/config/client.json:ro
  erp-consul:
    image: "hashicorp/consul:1.18.2"
    restart: unless-stopped
    command: "agent"
    volumes:
      - ./consul/server.json:/consul/config/server.json:ro
  inventory:
    image: "erp/inventory:latest"
    depends_on:
      - erp-mongodb
      - erp-consul
    restart: unless-stopped
  finances:
    image: "erp/finances:latest"
    depends_on:
      - erp-pg
      - rabbit
      - erp-consul
    restart: unless-stopped
  # SFTP has some weird issues with permissions, even tho I tell it to use my UID and GUID it is using
  # podman auto generated which requires full access on public (chmod 757 for example)
  sftp:
    image: "atmoz/sftp"
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    volumes:
      - /opt/sftp/erp-data:/home/erp/data:z
      - /opt/sftp/erp-conf/users.conf:/etc/sftp/users.conf:ro
    userns: keep-id
    privileged: true
  purchase-scanner:
    image: "erp/purchase-scanner:latest"
    environment:
      SFTP_HOST: "sftp"
      SFTP_USERNAME: "erp"
      SFTP_PASSWORD: "admin"
      RABBITMQ_HOST: "rabbit"
      RABBITMQ_USERNAME: "erp-user"
      RABBITMQ_PASSWORD: "admin"
    restart: unless-stopped
    depends_on:
      - sftp
      - rabbit
  analytics:
    image: "erp/analytics:latest"
    restart: unless-stopped
    depends_on: 
      - rabbit
      - erp-consul
  rabbit:
    image: "rabbitmq:3.13-management"
    volumes:
      - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbit/definitions.json:/etc/rabbitmq/definitions.json:ro
  nginx-proxy:
    image: "nginx:latest"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    ports:
      - "8000:80"
