server:
  port: 8084

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com:
      soitio: DEBUG

#feign:
#  client:
#    config:
#      default:
#        loggerLevel: full