#rabbitmq-username: analytics
#rabbitmq-password: analytics

mp:
  messaging:
    incoming:
      purchase_analytics_queue:
        connector: smallrye-rabbitmq
        queue:
          name: purchase_analytics_queue
          declare: false
        host: localhost
        port: 5672
        username: analytics
        password: analytics
#        exchange:
#          name: purchase_analytics_exchange

quarkus:
  log:
    level: DEBUG
  rabbitmq:
    devservices:
      enabled: false