server:
  port: 8080
  shutdown: graceful

spring:
  rabbitmq:
    host: rabbit
    port: 5672
    username: erp-user
    password: admin
  lifecycle:
    timeout-per-shutdown-phase: 5s

logging:
  level:
    com:
      soitio: DEBUG

#feign:
#  client:
#    config:
#      default:
#        loggerLevel: full