services:
  fe:
    image: "erp/fe:latest"
    ports:
      - "5100:3000"
    restart: unless-stopped
  erp-pg:
    image: "postgres:15.3-alpine3.18"
    environment:
      - POSTGRES_USER=erp
      - POSTGRES_PASSWORD=erp
    volumes:
      - /opt/postgres/erp-data:/var/lib/postgresql/data:Z
      - ./sql/initialize_finances.sql:/docker-entrypoint-initdb.d/initialize_finances.sql:Z
    restart: unless-stopped
    user: "$UID:$GID"
  erp-mongodb:
    image: "mongodb/mongodb-community-server:6.0.7-ubi8"
    volumes:
      - /opt/mongodb/erp-data:/data/db:Z
    environment:
      MONGO_INITDB_DATABASE: inventory
    restart: unless-stopped
    user: "$UID:$GID"
  consul-server-1:
    image: "consul:1.7"
    restart: unless-stopped
    command: "agent -server -retry-join erp-consul -client 0.0.0.0"
  erp-consul:
    image: "consul:1.7"
    restart: unless-stopped
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"
    ports:
      - "8555:8500"
  service-discovery:
    image: "erp/service-discovery:latest"
    depends_on:
      - erp-consul
    restart: unless-stopped
  inventory:
    image: "erp/inventory:latest"
    depends_on:
      - service-discovery
      - erp-mongodb
    restart: unless-stopped
  finances:
    image: "erp/finances:latest"
    depends_on:
      - service-discovery
      - erp-pg
    restart: unless-stopped
  # SFTP has some weird issues with permissions, even tho I tell it to use my UID and GUID it is using
  # podman auto generated which requires full access on public (chmod 757 for example)
  sftp:
    image: "atmoz/sftp"
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    volumes:
      - /opt/sftp/erp-data:/home/erp/data:z
      - /opt/sftp/erp-conf/users.conf:/etc/sftp/users.conf:ro
    userns: keep-id
    privileged: true
