server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    url: jdbc:postgresql://erp-pg:5432/finances?useUnicode=yes&characterEncoding=UTF-8
    username: finances
    password: finances
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  cloud:
    openfeign:
      client:
        config:
          self-register:
            url: http://erp-consul:8500
  rabbitmq:
    host: rabbit
    port: 5672
    username: erp-user
    password: admin
  lifecycle:
    timeout-per-shutdown-phase: 5s

logging:
  level:
    pl:
      mlisowski: DEBUG

#feign:
#  client:
#    config:
#      default:
#        loggerLevel: full

service-discovery:
  service-name: finances