server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    url: jdbc:postgresql://erp-pg:5432/finances?useUnicode=yes&characterEncoding=UTF-8
    username: finances
    password: finances
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  cloud:
    openfeign:
      client:
        config:
          gateway:
            url: http://gateway:8080/
  rabbitmq:
    host: rabbit
    port: 5672
    username: erp-user
    password: admin
  lifecycle:
    timeout-per-shutdown-phase: 5s

jakarta:
  persistence:
    jdbc:
      url: jdbc:postgresql://erp-pg:5432/finances?useUnicode=yes&characterEncoding=UTF-8

logging:
  level:
    com:
      soitio: DEBUG

#feign:
#  client:
#    config:
#      default:
#        loggerLevel: full

soitio:
  service: "http://finances:8080"
  dependencies: >
    com.soitio.finances.objectvalues.domain.ObjectValue,
    com.soitio.finances.moneyoperation.domain.MoneyOperation,
    com.soitio.finances.moneyoperation.periodical.domain.PeriodicalMoneyOperation,
    com.soitio.finances.plannedexpenses.domain.PlannedExpenses