server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finances?useUnicode=yes&characterEncoding=UTF-8
    username: finances
    password: finances
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  cloud:
    openfeign:
      client:
        config:
          self-register:
            url: http://localhost:8500/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jakarta:
  persistence:
    jdbc:
      url: jdbc:postgresql://localhost:5432/finances?useUnicode=yes&characterEncoding=UTF-8

logging:
  level:
    com:
      soitio: DEBUG

#feign:
#  client:
#    config:
#      default:
#        loggerLevel: full

service-discovery:
  service-name: finances
  host: localhost
  port: 8084

soitio:
  service: "http://localhost:8084"
  dependencies: >
    com.soitio.finances.objectvalues.domain.ObjectValue,
    com.soitio.finances.moneyoperation.domain.MoneyOperation,
    com.soitio.finances.moneyoperation.periodical.domain.PeriodicalMoneyOperation,
    com.soitio.finances.plannedexpenses.domain.PlannedExpenses