quarkus:
  http:
    port: 8080
  grpc:
    server:
      use-separate-server: false
  rest-client:
    "com.soitio.selfregister.client.RegistrationClient":
      url: http://erp-consul:8500
  shutdown:
    timeout: PT5S

service-discovery:
  service-name: reports-generator
  host: reports-generator
  port: 8080

report-service:
  host: localhost
  port: 8086