quarkus:
  http:
    port: 8080
  grpc:
    server:
      use-separate-server: false
  rest-client:
    "com.soitio.selfregister.self.register.quarkus.runtime.client.RegistrationClient":
      url: http://erp-consul:8500
  shutdown:
    timeout: PT5S

service-discovery:
  service-name: reports-generator
  host: reports-generator
  port: 8080

reports-service:
  host: reports-service
  port: 8080

sftp:
  host: sftp
  port: 22
  username: erp
  password: admin