quarkus:
  http:
    port: 8085
  grpc:
    server:
      use-separate-server: false
  rest-client:
    artifact-api:
      url: http://localhost:8089/
      scope: jakarta.inject.Singleton

reports-service:
  host: localhost
  port: 8086