quarkus:
  http:
    port: 8080
  grpc:
    server:
      use-separate-server: false
  shutdown:
    timeout: PT5S

reports-service:
  host: reports-service
  port: 8080

sftp:
  host: sftp
  port: 22
  username: erp
  password: admin