quarkus:
  http:
    port: 8085
  grpc:
    server:
      use-separate-server: false

reports-service:
  host: localhost
  port: 8086

sftp:
  host: localhost
  port: 2222
  username: erp
  password: admin