quarkus:
  http:
    port: 8086
  grpc:
    server:
      use-separate-server: false
  rest-client:
    "com.soitio.selfregister.self.register.quarkus.runtime.client.RegistrationClient":
      url: http://consul.soitio-erp.com:8000
    "com.soitio.reports.service.inventory.client.InventoryClient":
      url: http://localhost:8082
  datasource:
    db-kind: postgresql
    username: reports
    password: reports
    jdbc:
      url: jdbc:postgresql://localhost:5432/reports?useUnicode=yes&characterEncoding=UTF-8
  hibernate-orm:
    database:
      generation: update

service-discovery:
  service-name: reports-service
  host: localhost
  port: 8085

reports-generator:
  host: localhost
  port: 8085