quarkus:
  log:
    level: INFO
  http:
    port: 8080
  rest-client:
    http2: true
  mongodb:
    connection-string: mongodb://erp-mongodb:27017
    database: gateway

gateway:
  routes:
    FINANCES:
      hostname: finances
      port: 8080
    INVENTORY:
      hostname: localhost
      port: 8080