quarkus:
  log:
    level: INFO
  http:
    port: 8080
    limits:
      max-body-size: 100000000
  mongodb:
#    TODO: After it gets fixed, can create multiple reactive clients
#    https://github.com/quarkusio/quarkus/issues/45433
    connection-string: mongodb://erp-mongodb:27017
  grpc:
    server:
      use-separate-server: false
    clients:
      authService:
        host: gateway
        port: 8080
  generate-code:
    grpc:
      scan-for-proto: com.soitio:auth-client
  index-dependency:
    smallrye-jwt:
      group-id: io.smallrye
      artifact-id: smallrye-jwt

smallrye:
  jwt:
    sign:
      key:
          location: <private_key_location>
    encrypt:
      key:
        location: <public_key_location>
    new-token:
      issuer: https://soitio.com

mp:
  jwt:
    verify:
      publickey:
        location: <public_key_location>
      issuer: https://soitio.com

gateway:
  routes:
    FINANCES:
      hostname: finances
      port: 8080
    INVENTORY:
      hostname: inventory
      port: 8080
    PURCHASE-SCANNER:
      hostname: purchase-scanner
      port: 80
    WIDGETS_FINANCES:
      hostname: widgets-finances
      port: 8080
    DASHBOARD:
      hostname: dashboard
      port: 8080
    REPORTS:
      hostname: reports-service
      port: 8080
    ARTIFACT-MANAGER:
      hostname: artifact-manager
      port: 8080