quarkus:
  log:
    level: INFO
  http:
    port: 8070
    limits:
      max-body-size: 100000000
  mongodb:
    connection-string: mongodb://localhost:27017
  grpc:
    server:
      use-separate-server: false
    clients:
      authService:
        host: localhost
        port: 8070
  generate-code:
    grpc:
      scan-for-proto: com.soitio:auth-client

gateway:
  routes:
    FINANCES:
      hostname: localhost
      port: 8084
    INVENTORY:
      hostname: localhost
      port: 8082
    PURCHASE-SCANNER:
      hostname: localhost
      port: 8100
    WIDGETS_FINANCES:
      hostname: localhost
      port: 8080
    DASHBOARD:
      hostname: localhost
      port: 8083
    REPORTS:
      hostname: localhost
      port: 8086