quarkus:
  log:
    level: INFO
  http:
    port: 8080
  mongodb:
    connection-string: mongodb://erp-mongodb:27017
    database: gateway

gateway:
  routes:
    FINANCES:
      hostname: finances
      port: 8080
    INVENTORY:
      hostname: inventory
      port: 8080
    PURCHASE-SCANNER:
      hostname: purchase-scanner
      port: 80