quarkus:
  log:
    level: INFO
  http:
    port: 8070
  rest-client:
    http2: true
  mongodb:
    connection-string: mongodb://localhost:27017
    database: gateway

gateway:
  routes:
    FINANCES:
      hostname: localhost
      port: 8084
    INVENTORY:
      hostname: localhost
      port: 8082