quarkus:
  http:
    port: 8080
  mongodb:
    connection-string: mongodb://erp-mongodb:27017
    database: planner
  rest-client:
    "com.soitio.selfregister.client.RegistrationClient":
      url: http://erp-consul:8500
  shutdown:
    timeout: PT5S

service-discovery:
  service-name: planner
  host: planner
  port: 8080