quarkus:
  http:
    port: 8084
  mongodb:
    connection-string: mongodb://localhost:27017
    database: planner

  rest-client:
    "com.soitio.selfregister.self.register.quarkus.runtime.client.RegistrationClient":
      url: http://localhost:8080

service-discovery:
  service-name: planner
  host: localhost
  port: 8084
