quarkus:
  http:
    port: 8080
  rest-client:
    "com.soitio.widgets.startup.runtime.client.DashboardClient":
      url: http://dashboard:8080
    "com.soitio.widgets.finances.inventory.client.InventoryClient":
      url: http://inventory:8080
    "com.soitio.widgets.finances.client.FinancesClient":
      url: http://finances:8080
    "com.soitio.widgets.finances.client.FiltersDataClient":
      url: http://finances:8080
  shutdown:
    timeout: PT5S

widgets:
  widget-definitions:
    - name: Total Net Worth
      datasource: http://gateway:8080/api/widgets-finances/widgets/total-net-worth
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN001
    - name: Monthly Balance
      datasource: http://gateway:8080/api/widgets-finances/widgets/monthly-balance
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN002
    - name: Monthly Balance Diff
      datasource: http://gateway:8080/api/widgets-finances/widgets/monthly-balance-diff
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN003
      available-filters:
        - name: Year
          datasource: http://gateway:8080/api/widgets-finances/filters/balance/year
          mandatory: true
          filter-type: SELECT
        - name: Month
          depends-on:
            - Year
          datasource: http://gateway:8080/api/widgets-finances/filters/balance/month
          mandatory: true
          filter-type: SELECT
    - name: Most Expensive Item Per Category
      datasource: http://gateway:8080/api/widgets-finances/widgets/most-expensive-item-per-category
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN004
    - name: Value Per Category
      datasource: http://gateway:8080/api/widgets-finances/widgets/value-per-category
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN005
    - name: Remaining Planned Expenses For This Month
      datasource: http://gateway:8080/api/widgets-finances/widgets/remaining-planned-expenses
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN006