quarkus:
  http:
    port: 8080
  rest-client:
    "com.soitio.selfregister.self.register.quarkus.runtime.client.RegistrationClient":
      url: http://localhost:8500
    "com.soitio.widgets.startup.runtime.client.DashboardClient":
      url: http://localhost:8083
    "com.soitio.widgets.finances.inventory.client.InventoryClient":
      url: http://localhost:8082
    "com.soitio.widgets.finances.client.FinancesClient":
      url: http://localhost:8084
    "com.soitio.widgets.finances.client.FiltersDataClient":
      url: http://localhost:8084

service-discovery:
  service-name: widgets-finances
  host: localhost
  port: 8080

widgets:
  widget-definitions:
    - name: Total Net Worth
      datasource: http://localhost:8080/widgets/total-net-worth
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN001
    - name: Monthly Balance
      datasource: http://localhost:8080/widgets/monthly-balance
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN002
    - name: Monthly Balance Diff
      datasource: http://localhost:8080/widgets/monthly-balance-diff
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN003
      available-filters:
        - name: Year
          datasource: http://localhost:8080/filters/balance/year
          mandatory: true
          filter-type: SELECT
        - name: Month
          depends-on:
            - Year
          datasource: http://localhost:8080/filters/balance/month
          mandatory: true
          filter-type: SELECT
    - name: Most Expensive Item Per Category
      datasource: http://localhost:8080/widgets/most-expensive-item-per-category
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN004
    - name: Value Per Category
      datasource: http://localhost:8080/widgets/value-per-category
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN005
    - name: Remaining Planned Expenses For This Month
      datasource: http://localhost:8080/widgets/remaining-planned-expenses
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN006