quarkus:
  http:
    port: 8080
  rest-client:
    "pl.mlisowski.selfregister.client.RegistrationClient":
      url: http://localhost:8080
    "com.soitio.widgets.startup.runtime.client.DashboardClient":
      url: http://localhost:8083
    "com.soitio.widgets.finances.inventory.client.InventoryClient":
      url: http://localhost:8082
    "com.soitio.widgets.finances.client.FinancesClient":
      url: http://localhost:8084

service-discovery:
  service-name: widgets-finances
  host: localhost
  port: 8080

widgets:
  widget-definitions:
    - name: Total Net Worth
      datasource: http://localhost:8080/widgets/total-net-worth
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN001
    - name: Monthly Balance
      datasource: http://widgets-finances:8080/widgets/monthly-balance
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN002