quarkus:
  http:
    port: 8080
  rest-client:
    "pl.mlisowski.selfregister.client.RegistrationClient":
      url: http://erp-consul:8500
    "com.soitio.widgets.startup.runtime.client.DashboardClient":
      url: http://dashboard:8080
  shutdown:
    timeout: PT5S

service-discovery:
  service-name: widgets-finances
  host: widgets-finances
  port: 8080

widgets:
  widget-definitions:
    -
      name: Total Net Worth
      datasource: http://widgets-finances:8080/widgets/total-net-worth
      widget-domain: FINANCES
      version: v1.0
      unique-code: FIN001